<?php
namespace Clansuite;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-12 at 21:21:41.
 */
class ApplicationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Application
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new Application;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    }

    /**
     * @covers Clansuite\Application::run
     * @todo   Implement testRun().
     */
    public function testRun()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Clansuite\Application::define_ConstantsAndPaths
     * @todo   Implement testDefine_ConstantsAndPaths().
     */
    public function testDefine_ConstantsAndPaths()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Clansuite\Application::initialize_ConstantsAndPaths
     * @todo   Implement testInitialize_ConstantsAndPaths().
     */
    public function testInitialize_ConstantsAndPaths()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Clansuite\Application::initialize_Loader
     * @todo   Implement testInitialize_Loader().
     */
    public function testInitialize_Loader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Clansuite\Application::getInjector
     * @todo   Implement testGetInjector().
     */
    public function testGetInjector()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Clansuite\Application::getClansuiteConfig
     * @todo   Implement testGetClansuiteConfig().
     */
    public function testGetClansuiteConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Clansuite\Application::getEntityManager
     * @todo   Implement testGetEntityManager().
     */
    public function testGetEntityManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Clansuite\Application::triggerEvent
     * @todo   Implement testTriggerEvent().
     */
    public function testTriggerEvent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Clansuite\Application::shutdown
     * @todo   Implement testShutdown().
     */
    public function testShutdown()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
