<?php

/**
 * CsForumBoardsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Clansuite
 * @subpackage Database
 * @author     Clansuite - just an eSports CMS <vain at clansuite dot com>
 * @version    SVN: $Id: Builder.php 4601 2010-08-28 20:41:25Z vain $
 */
class CsForumBoardsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsForumBoardsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsForumBoards');
    }


    /**
     * fetchAllBoards
     *
     * Doctrine_Query to fetch all Forum Boards
     */
    public static function fetchAllBoards()
    {
        $result = Doctrine_Query::create()
                              ->select('b.*')
                              ->from('CsForumBoards b')
                              ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                              ->where('b.parent_id = 0')
                              ->orderby('b.sort DESC')
                              ->orderby('b.cat_id DESC')
                              ->execute( array() );

        return $result;;
    }

    /**
     * fetchSubBoards
     *
     * Doctrine_Query to fetch Forum SubBoards
     */
    public static function fetchSubBoards( $id )
    {
        $result = Doctrine_Query::create()
                              ->select('b.*')
                              ->from('CsForumBoards b')
                              ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                              ->where('b.parent_id = ' .$id)
                              ->orderby('b.sort DESC')
                              ->orderby('b.cat_id DESC')
                              ->execute( array() );

        return $result;;
    }

    /**
     * fetchAllForumParentBoardsByCategory
     */
    public static function fetchAllForumBoardsByCategory( $category )
    {
        $result = Doctrine_Query::create()
                              ->select('b.*')
                              ->from('CsForumBoards b')
                              ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                              ->where('b.cat_id = ' .$category)
                              ->execute( array() );

        return $result;;
    }

    /**
     * fetchAllForumSubBoards
     */
    public static function fetchAllForumSubBoards( $board_id )
    {
        $result = Doctrine_Query::create()
                              ->select('b.*, c.title as cat_title')
                              ->from('CsForumBoards b')
                              ->leftJoin('b.CsForumCategory c')
                              ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                              ->where('b.parent_id = ' .$board_id)
                              ->orderby('b.sort DESC')
                              ->execute( array() );

        return $result;;
    }

    /**
     * fetchAllForumBoardsByCategoryWidthPager
     *
     * Doctrine_Query to fetch Forum Boards by category
     * wrapped into the Doctrine_Pager
     */
    public static function fetchAllForumBoardsByCategoryWidthPager( $category, $currentPage, $resultsPerPage )
    {

        $pager_layout= new Doctrine_Pager_Layout(
                                new Doctrine_Pager(
                                    Doctrine_Query::create()
                                          ->select('b.*')
                                          ->from('CsForumBoards b')
                                          ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                                          ->where('b.cat_id = ' .$category)
                                          ->orderby('b.sort DESC'),
                                         $currentPage, # Current page of request
                                         $resultsPerPage  # (Optional) Number of results per page Default is 25
                                     ),
                                 new Doctrine_Pager_Range_Sliding(array(
                                     'chunk' => 5
                                    )),
                                 '?mod=forum&amp;action=boards&amp;page={%page}&amp;date='.$startdate
                                 );

        # Assigning templates for page links creation
        $pager_layout->setTemplate('[<a href="{%url}">{%page}</a>]');
        $pager_layout->setSelectedTemplate('[{%page}]');

        # Retrieving Doctrine_Pager instance
        $pager = $pager_layout->getPager();

        # Fetching news
        $boards = $pager->execute(array(), Doctrine::HYDRATE_ARRAY);

        # put things in an array-box for delivery multiple things with one return stmt
        return compact('boards', 'pager', 'pager_layout');

        return $result;;
    }

}