<?php

/**
 * CsUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsUsers');
    }


}