<?php

/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class CsNewsTable extends Doctrine_Table
{
    /**
     * fetchAllNews
     *
     * Doctrine_Query to fetch News by Category
     * wrapped into the Doctrine_Pager
     *
     * For Pager Chapter in Doctrine Manual
     * @link http://www.phpdoctrine.org/documentation/manual/0_10?one-page#utilities
     */
    public static function fetchAllNews($currentPage, $resultsPerPage)
    {
        # Creating Pager Object with a Query Object inside
        $pager_layout= new Doctrine_Pager_Layout(
                                new Doctrine_Pager(
                                    Doctrine_Query::create()
                                            ->select('n.*,
                                                      u.nick, u.user_id, u.email, u.country,
                                                      c.name, c.image, c.icon, c.color,
                                                      nc.*,
                                                      ncu.nick, ncu.email, ncu.country')
                                            ->addSelect('(SELECT COUNT(cc.comment_id) FROM CsNews ns LEFTJOIN ns.CsComments cc WHERE ns.news_id = n.news_id) as nr_news_comments')
                                            ->from('CsNews n')
                                            ->leftJoin('n.CsUsers u')
                                            ->leftJoin('n.CsCategories c')
                                            ->leftJoin('n.CsComments nc')
                                            ->leftJoin('nc.CsUsers ncu')
                                            ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                                            ->orderby('n.news_id DESC, n.created_at DESC'),
                                         # the following two values are the (sql) limit  ?,? =
                                         $currentPage, // Current page of request
                                         $resultsPerPage // (Optional) Number of results per page Default is 25
                                     ),
                                 new Doctrine_Pager_Range_Sliding(array(
                                     'chunk' => 5
                                    )),
                                 '?mod=news&amp;action=show&amp;page={%page}'
                                 );

        # Sets Layout of the pager links
        $pager_layout->setTemplate('[<a href="{%url}">{%page}</a>]');

        # Sets Layout of the pager
        $pager_layout->setSelectedTemplate('[{%page}]');

        # Retrieving Doctrine_Pager instance
        $pager = $pager_layout->getPager();

        # fetching the paginated news
        $news = $pager->execute(array(), Doctrine::HYDRATE_ARRAY);

        # put things in an array-box for delivery multiple things with one return stmt
        return array( 'news' => $news,
                      'pager'=> $pager,
                      'pager_layout' => $pager_layout
                    );
    }

    /**
     * fetchNewsByCategory
     *
     * Doctrine_Query to fetch News by Category
     */
    public static function fetchNewsByCategory($category, $currentPage, $resultsPerPage)
    {
        # Creating Pager Object with a Query Object inside
        $pager_layout = new Doctrine_Pager_Layout(
                                new Doctrine_Pager(
                                    Doctrine_Query::create()
                                            ->select('n.*,
                                                      u.nick, u.user_id, u.email, u.country,
                                                      c.name, c.image, c.icon, c.color,
                                                      nc.*,
                                                      ncu.nick, ncu.email, ncu.country')
                                            ->addSelect('(SELECT COUNT(cc.comment_id) FROM CsNews ns LEFTJOIN ns.CsComments cc WHERE ns.news_id = n.news_id) as nr_news_comments')
                                            ->from('CsNews n')
                                            ->leftJoin('n.CsUsers u')
                                            ->leftJoin('n.CsCategories c')
                                            ->leftJoin('n.CsComments nc')
                                            ->leftJoin('nc.CsUsers ncu')
                                            ->where('n.cat_id = ?', array( $category ) )
                                            ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                                            ->orderby('n.news_id DESC, n.created_at DESC'),
                                         # The following is Limit  ?,? =
                                         $currentPage, // Current page of request
                                         $resultsPerPage // (Optional) Number of results per page Default is 25
                                    ),
                                 new Doctrine_Pager_Range_Sliding(array(
                                     'chunk' => 5
                                    )),
                                 '?mod=news&amp;action=show&amp;page={%page}&amp;cat='.$category
                                 );

        # Set Layout of the pager links
        $pager_layout->setTemplate('[<a href="{%url}">{%page}</a>]');

        # Set Layout of the pager
        $pager_layout->setSelectedTemplate('[{%page}]');

        # Displaying pager links with cat added / 2nd parameter (true) surpresses the direct display
        #$pager_layout->display( array('cat' => urlencode($category)), true);

        # Retrieving Doctrine_Pager instance
        $pager = $pager_layout->getPager();

        # Fetching the paginated news
        $news = $pager->execute(array(), Doctrine::HYDRATE_ARRAY);

        # put things in an array-box for delivery multiple things with one return stmt
        return array( 'news' => $news,
                      'pager'=> $pager,
                      'pager_layout' => $pager_layout
                    );
    }

    /**
    * fetchNewsForFeed
    *
    * Doctrine_Query to fetch News by Category
    */
    public static function fetchNewsForFeed()
    {
        $news = Doctrine_Query::create()
                        ->select('n.*,
                                  u.nick, u.user_id, u.email, u.country,
                                  c.name, c.image, c.icon, c.color,
                                  nc.*,
                                  ncu.nick, ncu.email, ncu.country')
                        ->from('CsNews n')
                        ->leftJoin('n.CsUsers u')
                        ->leftJoin('n.CsCategories c')
                        ->leftJoin('n.CsComments nc')
                        ->leftJoin('nc.CsUsers ncu')
                        #->where('c.module_id = 7')
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                        ->fetchArray();

        # put things in an array-box for delivery multiple things with one return stmt
        return $news;
    }

    /**
     * fetchSingleNews
     *
     * Doctrine_Query to fetch News by Category
     */
    public static function fetchSingleNews($news_id)
    {
        $single_news = Doctrine_Query::create()
                    ->select('n.*,
                              u.nick, u.user_id, u.email, u.country,
                              c.name, c.image, c.icon, c.color,
                              nc.*,
                              ncu.nick, ncu.email, ncu.country')
                    ->from('CsNews n')
                    ->leftJoin('n.CsUsers u')
                    ->leftJoin('n.CsCategories c')
                    ->leftJoin('n.CsComments nc')
                    ->leftJoin('nc.CsUsers ncu')
                    #->where('c.module_id = 7')
                    ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                    ->where('news_id = ' . $news_id)
                    ->fetchArray();

        # put things in an array-box for delivery multiple things with one return stmt
        return $single_news;
    }

    /**
     * fetchNewsForFullArchiv
     *
     * Doctrine_Query to fetch News for Archiv
     */
    public static function fetchNewsForArchiv($startdate, $enddate, $currentPage, $resultsPerPage)
    {
        # Creating Pager Object with a Query Object inside
        $pager_layout= new Doctrine_Pager_Layout(
                                new Doctrine_Pager(
                                    Doctrine_Query::create()
                                            ->select('n.*,
                                                      u.nick, u.user_id, u.email, u.country,
                                                      c.name, c.image, c.icon, c.color,
                                                      nc.*,
                                                      ncu.nick, ncu.email, ncu.country')
                                            ->addSelect('(SELECT COUNT(cc.comment_id) FROM CsNews ns LEFTJOIN ns.CsComments cc WHERE ns.news_id = n.news_id) as nr_news_comments')
                                            ->from('CsNews n')
                                            ->leftJoin('n.CsUsers u')
                                            ->leftJoin('n.CsCategories c')
                                            ->leftJoin('n.CsComments nc')
                                            ->leftJoin('nc.CsUsers ncu')
                                            ->andWhere('n.created_at >= ?', array( $startdate ))
                                            ->andWhere('n.created_at <= ?', array( $enddate ))
                                            #->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                                            ->orderby('n.created_at'),
                                            # the following two values are the (sql) limit  ?,? =
                                         $currentPage, // Current page of request
                                         $resultsPerPage  // (Optional) Number of results per page Default is 25
                                     ),
                                 new Doctrine_Pager_Range_Sliding(array(
                                     'chunk' => 5
                                    )),
                                 '?mod=news&amp;action=archiv&amp;page={%page}&amp;date='.$startdate
                                 );

        // Assigning templates for page links creation
        $pager_layout->setTemplate('[<a href="{%url}">{%page}</a>]');
        $pager_layout->setSelectedTemplate('[{%page}]');

        // Retrieving Doctrine_Pager instance
        $pager = $pager_layout->getPager();

        // Fetching news
        $news = $pager->execute(array(), Doctrine::HYDRATE_ARRAY);
        #clansuite_xdebug::printR($news);
        # put things in an array-box for delivery multiple things with one return stmt
        return array( 'news' => $news,
                      'pager'=> $pager,
                      'pager_layout' => $pager_layout
                    );
    }

    /**
     * fetchNewsForFullArchiv
     *
     * Doctrine_Query to fetch News for Archiv
     */
    public static function fetchNewsForFullArchiv($sortorder, $startdate, $enddate, $currentPage, $resultsPerPage)
    {
        # Creating Pager Object with a Query Object inside
        $pager_layout= new Doctrine_Pager_Layout(
                                new Doctrine_Pager(
                                    Doctrine_Query::create()
                                            ->select('n.*,
                                                      u.nick, u.user_id, u.email, u.country,
                                                      c.name, c.image, c.icon, c.color,
                                                      nc.*,
                                                      ncu.nick, ncu.email, ncu.country')
                                            ->addSelect('(SELECT COUNT(cc.comment_id) FROM CsNews ns LEFTJOIN ns.CsComments cc WHERE ns.news_id = n.news_id) as nr_news_comments ')
                                            ->from('CsNews n')
                                            ->leftJoin('n.CsUsers u')
                                            ->leftJoin('n.CsCategories c')
                                            ->leftJoin('n.CsComments nc')
                                            ->leftJoin('nc.CsUsers ncu')
                                            ->andWhere('n.created_at >= ?', array( $startdate ))
                                            ->andWhere('n.created_at <= ?', array( $enddate ))
                                            #->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                                            ->orderby($sortorder),
                                         # the following two values are the (sql) limit  ?,? =
                                         $currentPage, // Current page of request
                                         $resultsPerPage  // (Optional) Number of results per page Default is 25
                                     ),
                                 new Doctrine_Pager_Range_Sliding(array(
                                     'chunk' => 5
                                    )),
                                 '?mod=news&amp;action=fullarchiv&amp;page={%page}&amp;date='.$startdate
                                 );
        // Assigning templates for page links creation
        $pager_layout->setTemplate('[<a href="{%url}">{%page}</a>]');
        $pager_layout->setSelectedTemplate('[{%page}]');

        // Retrieving Doctrine_Pager instance
        $pager = $pager_layout->getPager();

        // Fetching news
        $news = $pager->execute(array(), Doctrine::HYDRATE_ARRAY);

        # put things in an array-box for delivery multiple things with one return stmt
        return array( 'news' => $news,
                      'pager'=> $pager,
                      'pager_layout' => $pager_layout
                    );
    }

    /**
     * fetchLatestNews
     *
     * Doctrine_Query to fetch Latest News
     */
    public static function fetchLatestNews($numberNews)
    {
        # fetch news via doctrine query
        $latestnews = Doctrine_Query::create()
                              ->select('n.*, u.nick, u.user_id, c.name, c.image')
                              ->from('CsNews n')
                              ->leftJoin('n.CsUsers u')
                              ->leftJoin('n.CsCategories c')
                              ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                              ->orderby('n.news_id DESC')
                              ->limit($numberNews)
                              ->execute( array() );

        # put things in an array-box for delivery multiple things with one return stmt
        return $latestnews;
    }

    /**
     * fetch News Categories for List-Style
     *
     * Doctrine_Query to fetch News Categories
     */
    public static function fetchNewsCategoriesList()
    {
        # fetch news via doctrine query
        $newscategories_list = Doctrine_Query::create()
                                    ->select('n.cat_id, COUNT(n.cat_id) sum, c.name')
                                    ->from('CsNews n')
                                    ->innerJoin('n.CsCategories c ON n.cat_id = c.cat_id')
                                    ->where('c.module_id = 7')
                                    ->groupBy('c.name')
                                    ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                                    ->execute( array() );

        return $newscategories_list;
    }

    /**
     * fetch News Categories for Dropdown-Style
     *
     * Doctrine_Query to fetch News Categories
     */
    public static function fetchNewsCategoriesDropdown()
    {
        # fetch news via doctrine query
        $newscategories_dropdown = Doctrine_Query::create()
                                    ->select('n.cat_id, COUNT(n.cat_id) sum, c.name')
                                    ->from('CsNews n')
                                    ->innerJoin('n.CsCategories c ON n.cat_id = c.cat_id')
                                    ->where('c.module_id = 7')
                                    ->groupBy('c.name')
                                    ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                                    ->execute( array() );


        return $newscategories_dropdown;
    }

    public static function fetchNewsArchiveWidget()
    {
        # fetch all newsentries, ordered by creation date ASCENDING
        $widget_archive = Doctrine_Query::create()
                                    ->select('n.news_id, n.created_at')
                                    ->from('CsNews n')
                                    ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                                    ->orderby('n.created_at ASC')
                                    ->execute( array() );

        return $widget_archive;
    }
}
?>