<?php

/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class CsMatchesTable extends Doctrine_Table
{
    public function fetchTopmatch()
    {
        return Doctrine_Query::create()
               ->select('m.*')
               ->from('CsMatches m')
               ->fetchOne();
    }

    public function fetchLatestMatches($number)
    {
        return Doctrine_Query::create()
               ->select('m.*')
               ->from('CsMatches m')
               ->orderby('m.matchdate DESC')
               ->where('m.matchdate < ?', time() )
               ->limit($number)
               ->fetchArray();
    }

    public function fetchNextMatches($number)
    {
        return Doctrine_Query::create()
               ->select('m.*')
               ->from('CsMatches m')
               ->orderby('m.matchdate DESC')
               ->where('m.matchdate < ?', time() )
               ->limit($number)
               ->fetchArray();
    }
}
?>