#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.3.x version
  # - 5.3
  # aliased to a recent 5.4.x version
  - 5.4

before_install:
  # install all git submodules (and nested git submodules)
  - git submodule update --init --recursive

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - composer install --dev

# execute !!!
script:
 - output=$(php ./bin/php-cs-fixer/php-cs-fixer.phar fix -v --level=all --dry-run .); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;
 # run unit-tests
 - php ./tests/runAllTests.php
 # ensure that encoding of framework files is UTF8
 # - ./build-tools/checkEncodingUTF8.sh framework

# configure notifications (email, irc etc)
notifications:
  email: false
  irc:
    - "irc.freenode.org#koch"
    - "irc.quakenet.org#clansuite"