#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4

# optionally specify a list of environments, for example to test different RDBMS
env:
  #- DB=mysql
  #- DB=pgsql
  #- DB=sqlite

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  # install composer
  #- curl -s http://getcomposer.org/installer | php
  #- php composer.phar install
  # configure database
  #- sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS ci_test;' -U postgres; fi"
  #- sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database ci_test;' -U postgres; fi"
  #- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS ci_test;'; fi"
  # install php-cs-fixer
  wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

# execute !!!
script:
 # run unit-tests
 - ./tests/runTests.sh
 # run php-cs-fixer
 - output=$(php php-cs-fixer.phar fix -v --level=all --dry-run .); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;

# let CI take only the "develop" branch into account
#branches:
#  only:
#    - develop

# configure notifications (email, irc etc)
notifications:
  irc: "irc.freenode.org#clansuite"
  irc: "jubii.dk.quakenet.org#clansuite"