<?php /* Smarty version 2.6.13, created on 2006-06-17 04:52:26
         compiled from index.tpl */

$this->_cache_serials['D:/Homepage/clansuite.com/workplace/trunk/core/smarty/templates_c/\%%45^45E^45E480CD%%index.tpl.inc'] = '482dc094f34c2788636733bb157bc202';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'mod', 'index.tpl', 79, false),)), $this); ?>
<?php
function _smarty_tplfunc_482dc094f34c2788636733bb157bc202_0(&$_smarty)
{
echo modules::get_instant_content(array('name' => 'index','func' => 'index_time','params' => "english|-"), $_smarty);
}



?>
