<?php /* Smarty version 2.6.13, created on 2006-06-08 12:19:13
         compiled from security_breach.tpl */

$this->_cache_serials['D:/Homepage/clansuite.com/workplace/trunk/core/smarty/templates_c/\%%C2^C2D^C2D961EF%%security_breach.tpl.inc'] = 'e940a2edd6415eadb77078c130e3f703';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'translate', 'security_breach.tpl', 14, false),)), $this); ?>
<?php
function _smarty_tplfunc_e940a2edd6415eadb77078c130e3f703_0(&$_smarty)
{
$_smarty->_tag_stack[] = array('translate', array()); $_block_repeat=true;language::smarty_translate($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], null, $_smarty, $_block_repeat);while ($_block_repeat) { ob_start(); ?>SECURITY BREACH!<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo language::smarty_translate($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], $_block_content, $_smarty, $_block_repeat); }  array_pop($_smarty->_tag_stack); 
}


function _smarty_tplfunc_e940a2edd6415eadb77078c130e3f703_1(&$_smarty)
{
$_smarty->_tag_stack[] = array('translate', array()); $_block_repeat=true;language::smarty_translate($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], null, $_smarty, $_block_repeat);while ($_block_repeat) { ob_start(); ?>There seems to be an hacking attempt or unusual failure in progress...<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo language::smarty_translate($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], $_block_content, $_smarty, $_block_repeat); }  array_pop($_smarty->_tag_stack); 
}


function _smarty_tplfunc_e940a2edd6415eadb77078c130e3f703_2(&$_smarty)
{
$_smarty->_tag_stack[] = array('translate', array()); $_block_repeat=true;language::smarty_translate($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], null, $_smarty, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Every step is logged and the webmaster is informed about the problem.<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo language::smarty_translate($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], $_block_content, $_smarty, $_block_repeat); }  array_pop($_smarty->_tag_stack); 
}



?>
