<?php /* Smarty version 2.6.13, created on 2006-06-08 05:34:25
         compiled from index/show.tpl */

$this->_cache_serials['D:/Homepage/clansuite.com/workplace/trunk/core/smarty/templates_c/\%%E5^E5D^E5DC63F6%%show.tpl.inc'] = 'c376b988b81e8d8a827009f1b94f101a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'translate', 'index/show.tpl', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_c376b988b81e8d8a827009f1b94f101a_0(&$_smarty)
{
$_smarty->_tag_stack[] = array('translate', array()); $_block_repeat=true;language::smarty_translate($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], null, $_smarty, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Hello<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo language::smarty_translate($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], $_block_content, $_smarty, $_block_repeat); }  array_pop($_smarty->_tag_stack); 
}


function _smarty_tplfunc_c376b988b81e8d8a827009f1b94f101a_1(&$_smarty)
{
$_smarty->_tag_stack[] = array('translate', array()); $_block_repeat=true;language::smarty_translate($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], null, $_smarty, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Welcome<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo language::smarty_translate($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], $_block_content, $_smarty, $_block_repeat); }  array_pop($_smarty->_tag_stack); 
}


function _smarty_tplfunc_c376b988b81e8d8a827009f1b94f101a_2(&$_smarty)
{
$_smarty->_tag_stack[] = array('translate', array('u' => 'Benutzernamen_variable')); $_block_repeat=true;language::smarty_translate($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], null, $_smarty, $_block_repeat);while ($_block_repeat) { ob_start(); ?>How are you, %u ?<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo language::smarty_translate($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], $_block_content, $_smarty, $_block_repeat); }  array_pop($_smarty->_tag_stack); 
}



?>
