////////////////////////////////////////////////////////////////////////////////

This file belongs to "Clansuite - just an eSports CMS" as part of the "Clansuite Documentation".
This file is written in ASCIIDOC format. It's dual-licensed under the GNU Free Documentation License,
Version 1.3 and the Creative Commons Attribution-Share-Alike 3.0 License (cc-by-sa).

You find a comprehensive AsciiDoc UserGuide here:
http://www.methods.co.nz/asciidoc/userguide.html

You find a Ascii Doc SheetCheat here:
http://powerman.name/doc/asciidoc-compact

For the Clansuite Documentation visit:
http://docs.clansuite.com/

SVN: $Id$

////////////////////////////////////////////////////////////////////////////////

== Kapitel 4 - Grundlegende Orientierung und Verzeichnisübersicht

Dieses Kapitel gibt Ihnen einen Überblick über die Struktur von Clansuite.

=== Grundlegende Orientierung

==== Dateien im Wurzelverzeichnis

Nach der Installation von Clansuite finden Sie die folgende Dateien im Hauptverzeichnis von Clansuite vor:

[source,txt]
--------------------------------------------------------------------------------
.htaccess      Beinhaltet Anweisungen für den Apache Webserver
index.php      Der zentrale Applikationseinstieg. Die Datei nimmt alle Anfragen des Browsers entgegen.
robots.txt     Steuerungsdatei für Webcrawler. Sie enthält Anweisung für das Indexieren von Dateien und Verzeichnissen.
--------------------------------------------------------------------------------

==== Verzeichnisübersicht

Sie finden die folgende Verzeichnisstruktur vor:

[source,txt]
--------------------------------------------------------------------------------
clansuite
+---build-tools         Beinhaltet die Phing Build-File und Shell-Scripte für das Builden, sowie Konfigurationsdateien für Werkzeuge.
+---cache               Ist das Verzeichnis für temporär zwischengespeicherte Daten der Anwendung.
+---configuration       Beinhaltet die allgemeine Konfigurationsdatei "clansuite.config.php" und zusätzliche Konfigurationsdateien.
+---core                Beinhaltet den Clansuite Anwendungskern.
+---doc                 Beinhaltet die Dokumentation, sowie diverse rein informative Textdateien, unter anderem die Autorenliste und
¦                       die Lizenztexte von Clansuite. Ein Vorhandensein dieser Dateien ist nicht notwendig, um Clansuite zu betreiben.
+---modules             Beinhaltet alle verfügbaren Module des Systems. Hierher werden neue Module installiert.
+---themes              Beinhaltet alle Themes. Hierher werden neue Themes installiert.
--------------------------------------------------------------------------------

===== Core

[source,txt]
--------------------------------------------------------------------------------
+---core                Beinhaltet den Clansuite Anwendungskern.
¦   +---bootstrap       Beinhaltet die für den Systemstart wesentlichen Kernfunktionen (Loading, Application Start).
¦   +---cache           Das Verzeichnis der Caching-Adapter.
¦   +---cronjobs        Das Verzeichnis für Cronjobs/Crontasks.
¦   +---debug           Das Verzeichnis für Debugging Hilfsfunktionen.
¦   +---events          Das Verzeichnis für Events.
¦   +---factories       Das Verzeichnis der Fabriken (für Cache, Config, Logger und Renderer).
¦   +---filter          Das Verzeichnis für Vor- und Nachfilter.
¦   +---functions       Beinhaltet hilfreiche zusätzliche Funktionen.
¦   +---gettext         Beinhaltet die Unterstützungklassen zur Arbeit mit Gettext.
¦   +---logger          Das Verzeichnis der Logging-Adapter.
¦   +---render          Das Verzeichnis der Renderer-Adapter.
¦   +---viewhelper      Das Verzeichnis für Hilfsfunktionen im View.
¦       +---smarty      Das Verzeichnis der Clansuite Viewhelper für die Renderengine Smarty.
--------------------------------------------------------------------------------

===== Themes

Das Verzeichnis Themes enthält zunächst die drei Verzeichnisse frontend, backend und core.
Frontend-Themes liegen in eigenen Verzeichnissen unterhalb von /themes/frontend.
Backend-Themes liegen in eigenen Verzeichnissen unterhalb von /themes/backend.
Systemweit verfügbare Bilder, Javascript, CSS, Schriften und Templates werden 
unterhalb von /themes/core in jeweils eigenen Verzeichnissen abgelegt.

[source,txt]
--------------------------------------------------------------------------------
+---themes              Hauptverzeichnis für Themes. 
¦   +---frontend        Unterverzeichnis für Frontend-Themes.
¦       +---xyz         Verzeichnis eines Frontend-Themes.
¦   +---backend         Unterverzeichnis für Frontend-Themes.
¦       +---xyz         Verzeichnis eines Backend-Themes.
¦   +---core            Beinhaltet die Themes des Clansuite-Kerns.
¦   ¦   +---css         Verzeichnis für systemweit verfügbare Cascading Style Sheets/Bibliotheken.
¦   ¦   +---exceptions  Beinhaltet Exceptiontemplates.
¦   ¦   +---fonts       Beinhaltet Schriften.
¦   ¦   +---javascript  Verzeichnis für systemweit verfügbares Javascript und Bibliotheken.
¦   ¦   +---templates   Beinhaltet System-Templates.
--------------------------------------------------------------------------------

===== Modules

Sie finden die folgende Grundstruktur im Bereich Module vor:

[source,txt]
--------------------------------------------------------------------------------
+---modules             Beinhaltet alle verfügbaren Module des Systems. Hierher werden neue Module installiert.
¦   +---modulename      Verzeichnis eines Moduls
¦   ¦   +---model       Models (ActiveRecords/UnitsOfWork)
¦   ¦   +---view        View
¦   ¦   +---controller  Controller
--------------------------------------------------------------------------------