<?php

/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class CsShoutboxTable extends Doctrine_Table
{
    public function fetchAll($number)
    {
        return Doctrine_Query::create()
               ->select('s.*')
               ->from('CsShoutbox s')
               ->limit($number)
               ->fetchArray();
    }
}
?>