                            _________________________
                            C  L  A  N  S  U  I  T  E
                         _______________________________
                         D E V E L O P M E N T   T E A M



For a detailed list of Development Team Members with SVN Access visit:
    https://gna.org/project/memberlist.php?group=clansuite

For the project history visit:
    https://gna.org/project/admin/history.php?group=clansuite

For the contributors list based on svn commits visit:
    http://www.ohloh.net/p/clansuite/contributors

Clansuite is developed by:

========================================================================================================================
#  Name                       Nick              Email                           Time/Action GNA-History
   Position
========================================================================================================================

1  Jens-André Koch            vain              jakoch@web.de

   Founder & Headdeveloper .................................................... project founder (2005)
                                                                                (+) joined 18.05.2006
   Maintainer & Benevolent Dictator ........................................... (+) 28.01.2008

------------------------------------------------------------------------------------------------------------------------

2  Florian Wolf               xsign             xsign.dll@clansuite.com

   Headdeveloper .............................................................. (+) GNA Added User 19.05.2006 vain
                                                                                    break from 05.2007 on
                                                                                (-) left 15.10.2007
                                                                                (-) GNA Removed User 28.01.2008 vain
                                                                                    joined Clansphere Project
   Developer / Serveradministration ........................................... (+) GNA Added User 04.04.2008 vain
                                                                                    break from 09.2008 on
   Developer ..................................................................     Januar 2010
                                                                                active Jan/Feb 2010
                                                                                (-) GNA Removed User 13.02.2010 vain
   R                                                                                Reason:  commit behaviour

------------------------------------------------------------------------------------------------------------------------

3  Tino Goratsch              vyper             tinogo@blue-cable.de

   Developer .................................................................. (+) GNA Approved User 14.02.2007 vain
                                                                                    break from 11.2009 on
   I                                                                                inactive
                                                                                (-) GNA Removed User 26.05.2010 vain
   R                                                                                Reason: inactive

------------------------------------------------------------------------------------------------------------------------

4  Pasqual Eusterfeldhus      thunderm00n

   Bugs, Documentation, Themes, Graphics ...................................... (+) GNA Approved User 02.08.2008 vain
                                                                                    break from 09.2008 on
                                                                                    break from 12.2009 on
   I                                                                                inactive 04.2010, user request

------------------------------------------------------------------------------------------------------------------------

5  Daniel Winterfeldt         rikku             rikku@gna.org

   Developer .................................................................. (+) GNA Approved User 10.12.2008 vain
                                                                                (-) GNA Removed User 07.12.2009 vain
   R                                                                                Reason: inactive, user request

------------------------------------------------------------------------------------------------------------------------

6  Paul Brand                 paulbr            paulbr@gna.org

   Developer .................................................................  (+) GNA Approved User 04.11.2010 vain

------------------------------------------------------------------------------------------------------------------------

7  Tobias Fichtner            tobiasfichnter    tobiasfichtner@gna.org

   Developer .................................................................. (+) GNA Approved User 06.10.2011 vain

------------------------------------------------------------------------------------------------------------------------