<?php
namespace Koch\Config;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-12 at 22:36:31.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Config
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new Config;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    }

    /**
     * @covers Koch\Config\Config::readConfig
     * @todo   Implement testReadConfig().
     */
    public function testReadConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Config\Config::readModuleConfig
     * @todo   Implement testReadModuleConfig().
     */
    public function testReadModuleConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Config\Config::writeModuleConfig
     * @todo   Implement testWriteModuleConfig().
     */
    public function testWriteModuleConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Config\Config::writeConfig
     * @todo   Implement testWriteConfig().
     */
    public function testWriteConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
