<?php
namespace Koch\Config;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-12 at 22:36:30.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Factory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new Factory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    }

    /**
     * @covers Koch\Config\Factory::determineConfigurationHandlerTypeBy
     * @todo   Implement testDetermineConfigurationHandlerTypeBy().
     */
    public function testDetermineConfigurationHandlerTypeBy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Config\Factory::getConfiguration
     * @todo   Implement testGetConfiguration().
     */
    public function testGetConfiguration()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Config\Factory::getHandler
     * @todo   Implement testGetHandler().
     */
    public function testGetHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Config\Factory::getConfigurationHandler
     * @todo   Implement testGetConfigurationHandler().
     */
    public function testGetConfigurationHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
