<?php
namespace Koch\Config\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-12 at 22:36:31.
 */
class XMLTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var XML
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new XML($this->getFile());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    }

    public function getFile()
    {
        return dirname(__DIR__) . '/fixtures/data.xml';
    }

    /**
     * @covers Koch\Config\Adapter\XML::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Config\Adapter\XML::writeConfig
     * @todo   Implement testWriteConfig().
     */
    public function testWriteConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Config\Adapter\XML::readConfig
     * @todo   Implement testReadConfig().
     */
    public function testReadConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
