<?php
namespace Koch\Config\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-12 at 22:36:32.
 */
class YAMLTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var YAML
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        if ((extension_loaded('syck') === false) xor (is_file(ROOT_LIBRARIES . '/spyc/Spyc.class.php') === true)) {
            $this->markTestSkipped('The no yaml reader available. Install SYCK extensions or Spyc library.');
            $this->expectException();
        }

        $this->object = new YAML($this->getFile());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    }

    public function getFile()
    {
        return dirname(__DIR__) . '/fixtures/data.yml';
    }

    /**
     * @covers Koch\Config\Adapter\YAML::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Config\Adapter\YAML::writeConfig
     * @todo   Implement testWriteConfig().
     */
    public function testWriteConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Config\Adapter\YAML::readConfig
     * @todo   Implement testReadConfig().
     */
    public function testReadConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
