<?php

/**
 * CsAclRolesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsAclRolesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsAclRolesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsAclRoles');
    }
}