<?php

/**
 * CsAclRulesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsAclRulesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsAclRulesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsAclRules');
    }
}