<?php

/**
 * CsBbCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsBbCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsBbCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsBbCode');
    }
}