<?php

/**
 * CsCalendarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsCalendarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsCalendarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsCalendar');
    }
}