<?php

/**
 * CsCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsComments');
    }
}