<?php

/**
 * CsGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsGroups');
    }
}