<?php

/**
 * CsImagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsImagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsImagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsImages');
    }
}