<?php

/**
 * CsMessagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsMessagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsMessagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsMessages');
    }
}