<?php

/**
 * CsNewsIndexTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsNewsIndexTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsNewsIndexTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsNewsIndex');
    }
}