<?php

/**
 * CsOptionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsOptionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsOptionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsOptions');
    }
}