<?php

/**
 * CsOpponentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsOpponentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsOpponentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsOpponents');
    }
}