<?php

/**
 * CsProfilesComputerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsProfilesComputerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsProfilesComputerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsProfilesComputer');
    }
}