<?php

/**
 * CsProfilesGeneralTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsProfilesGeneralTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsProfilesGeneralTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsProfilesGeneral');
    }
}