<?php

/**
 * CsProfilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsProfilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsProfilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsProfiles');
    }
}