<?php

/**
 * CsProfilesGuestbookTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsProfilesGuestbookTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsProfilesGuestbookTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsProfilesGuestbook');
    }
}