<?php

/**
 * CsQuotesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsQuotesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsQuotesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsQuotes');
    }
}