<?php

/**
 * CsRelUserProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsRelUserProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsRelUserProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsRelUserProfile');
    }
}