<?php

/**
 * CsRelOptionNameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsRelOptionNameTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsRelOptionNameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsRelOptionName');
    }
}