<?php

/**
 * CsRelUserOptionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsRelUserOptionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsRelUserOptionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsRelUserOptions');
    }
}