<?php

/**
 * CsSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsSettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsSettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsSettings');
    }
}