<?php

/**
 * CsSessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsSessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsSessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsSession');
    }
}