<?php

/**
 * CsServerviewerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsServerviewerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsServerviewerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsServerviewer');
    }
}