<?php

/**
 * CsUsersOptionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsUsersOptionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsUsersOptionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsUsersOptions');
    }
}