<?php

/**
 * CsWhowasonlineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsWhowasonlineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsWhowasonlineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsWhowasonline');
    }
}