<?php

/**
 * CsWhoisonlineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CsWhoisonlineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CsWhoisonlineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CsWhoisonline');
    }
}