<?php

/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class CsCategroiesTable extends Doctrine_Table
{
    public function fetchAllCategories()
    {
        return Doctrine_Query::create()
               ->select('c.*')
               ->from('CsCategories c')
               ->fetchArray();
    }
}
?>