<?php

/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class CsCategoriesTable extends Doctrine_Table
{
    public static function fetchAll()
    {
        return Doctrine_Query::create()
               ->select('c.*')
               ->from('CsCategories c')
               ->fetchArray();
    }
	
	public static function fetchAllCategories($sortorder)
	{
        return Doctrine_Query::create()
               ->select('c.*, m.name as module')
               ->from('CsCategories c')
			   ->leftJoin('c.CsModules m on c.module_id = m.module_id')
			   ->orderby($sortorder)
               ->fetchArray();
	}
}
?>