<?php

/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class CsDownloadsTable extends Doctrine_Table
{
    public function fetchTopFiles($number)
    {
        return Doctrine_Query::create()
               ->select('m.*')
               ->from('CsDownloads m')
               ->orderby('m.download_rating DESC')
               ->limit($number)
               ->fetchArray();
    }

    public function fetchLatestFiles($number)
    {
        return Doctrine_Query::create()
               ->select('m.*')
               ->from('CsDownloads m')
               ->orderby('m.added_date DESC')
               ->where('m.added_date < ?', time() )
               ->limit($number)
               ->fetchArray();
    }

    public function fetchAllDownloads()
    {
        return Doctrine_Query::create()
               ->select('m.*')
               ->from('CsDownloads m')
               ->fetchArray();
    }
}
?>