<?php
namespace Koch\Debug;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-14 at 00:58:52.
 */
class DebugTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Debug
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new Debug;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    }

    /**
     * @covers Koch\Debug\Debug::printR
     * @todo   Implement testPrintR().
     */
    public function testPrintR()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Debug\Debug::dump
     * @todo   Implement testDump().
     */
    public function testDump()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Debug\Debug::firebug
     * @todo   Implement testFirebug().
     */
    public function testFirebug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Debug\Debug::getOriginOfDebugCall
     * @todo   Implement testGetOriginOfDebugCall().
     */
    public function testGetOriginOfDebugCall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Debug\Debug::getIncludedFiles
     * @todo   Implement testGetIncludedFiles().
     */
    public function testGetIncludedFiles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Debug\Debug::getApplicationConstants
     * @todo   Implement testGetApplicationConstants().
     */
    public function testGetApplicationConstants()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Debug\Debug::getBacktrace
     * @todo   Implement testGetBacktrace().
     */
    public function testGetBacktrace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Debug\Debug::getInterfaces
     * @todo   Implement testGetInterfaces().
     */
    public function testGetInterfaces()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Debug\Debug::getClasses
     * @todo   Implement testGetClasses().
     */
    public function testGetClasses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Debug\Debug::getFunctions
     * @todo   Implement testGetFunctions().
     */
    public function testGetFunctions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Debug\Debug::getExtensions
     * @todo   Implement testGetExtensions().
     */
    public function testGetExtensions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Debug\Debug::getPhpIni
     * @todo   Implement testGetPhpIni().
     */
    public function testGetPhpIni()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Debug\Debug::getWrappers
     * @todo   Implement testGetWrappers().
     */
    public function testGetWrappers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Debug\Debug::getRegisteredEventListeners
     * @todo   Implement testGetRegisteredEventListeners().
     */
    public function testGetRegisteredEventListeners()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
