<?php
namespace Koch\Code;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-12 at 21:37:21.
 */
class ReflectionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Reflection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new Reflection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    }

    /**
     * @covers Koch\Code\Reflection::getClassName
     * @todo   Implement testGetClassName().
     */
    public function testGetClassName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Code\Reflection::getMethods
     * @todo   Implement testGetMethods().
     */
    public function testGetMethods()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
